### ISSUE TITLE
Data missing when refetching

### ISSUE THREAD

**Issue by zekenie** [kevinschaich/mintable#100]
I messed up my initial sheet, so I thought I'd make a new one. I added some new accounts. Now when I fetch transactions, it feels like there's a ton of missing data. It seems like recent months are mostly complete, but if I go back a few months it only has 2 transactions per month. Does Plaid only give you some transactions once? Is there some cache somewhere on my local file system that's saying "this transaction's already logged"

**Comment by kevinschaich** [comment]
Hey @zekenie – neither Plaid nor Mintable keep any record of which transactions have been fetched so far.

What version are you on? How far back are you pulling? I think some banks cap out at ~6 months of full history.

**Comment by zekenie** [comment]
Hey, thanks for getting back to me. That totally might explain some of it. But, I feel like there's still some weirdness? Hard to put my finger on. First I ran the script with only one account, and things looked pretty complete. Then I ran it with two accounts, and stuff got weirder. The charts made less sense, and it felt like there were too few rows.

**Comment by kevinschaich** [comment]
Can you answer [the above questions here](https://github.com/kevinschaich/mintable/issues/100#issuecomment-662064544)?

Try removing all but the "later" accounts which seemed to be causing problems on a new sheet?

If you get a similar amount of rows, I think it's that your bank and Plaid not playing nicely and only supporting a finite amount of history.

**Comment by kevinschaich** [comment]
Hey @zekenie just checking in here – do you still need help on this?

**Comment by zekenie** [comment]
Apologies, I'm good. I think the discrepancies I'm seeing are what you described... just not having data very far back. When I run it consistently it seems to work well
