### ISSUE TITLE
Public key?

### ISSUE THREAD

**Issue by jfaust** [kevinschaich/mintable#101]
I'm going through setup for the first time, and I'm not sure where to find the public key - https://dashboard.plaid.com/team/keys has the Client ID, and the Development Secret, but no public key.

Is this something that has changed w/Plaid recently?

**Comment by jfaust** [comment]
Looks like this is a change to the Plaid API: https://github.com/plaid/plaid-node/pull/310

**Comment by kevinschaich** [comment]
Thanks a ton @jfaust – here's what I'm seeing on that link since I had an account before migrating:

![image](https://user-images.githubusercontent.com/9244728/88595589-43576f80-d031-11ea-9305-0f22568b9d08.png)

What version of mintable are you running btw?

**Comment by jfaust** [comment]
I was trying out `v2`, since it didn't seem useful to start fresh w/`v1` right now.

**Comment by kevinschaich** [comment]
Gonna try to check this out this weekend.

**Comment by kevinschaich** [comment]
Hey @jfaust I believe this should be resolved in #102 / `v2.0.0-beta.47`!

Mind testing out the fix for me?

**Comment by jfaust** [comment]
Works great! Thanks!
