### ISSUE TITLE
Template Creation?

### ISSUE THREAD

**Issue by Epod** [kevinschaich/mintable#112]
Greetings,

It seems most of the guides out there for making a google doc template are for v1.0

What is the procedure for creating a google doc template for 2.0? I am leveraging Github Actions

**Comment by kevinschaich** [comment]
Hey @Epod – docs for GitHub Actions are here:

https://github.com/kevinschaich/mintable/blob/master/docs/README.md#automatically-in-the-cloud--via-github-actions
