### ISSUE TITLE
Plaid Supported Countries

### ISSUE THREAD

**Issue by okwilkins** [kevinschaich/mintable#118]
https://github.com/kevinschaich/mintable/blob/d5eadf6ec321cc6897ec915174f3280ffda4f541/src/integrations/plaid/plaidIntegration.ts#L126

Hi! Are there any plans on using US & GB here? It would be nice to have support for more than just the US!
I did some testing with just 'GB'. Plaid seems to fetch the data correctly, but then it doesn't edit Sheet 1 at all.

**Comment by lecoffeeguy** [comment]
I tried as well changing it to other country_codes. But still only get US banks.. Any idea how to solve that?

**Comment by jacobdtapper** [comment]
Once you've installed through npm install go to mintable\lib\integrations\plaid\plaidIntegration.js and change line 179:

`country_codes: ['US'],` to your country. 

Do the same in mintable\lsrc\integrations\plaid\plaidIntegration.js, line 126.

You should then be able to add accounts from a new country.

**Comment by lecoffeeguy** [comment]
> Once you've installed through npm install go to mintable\lib\integrations\plaid\plaidIntegration.js and change line 179:
> 
> `country_codes: ['US'],` to your country.
> 
> Do the same in mintable\lsrc\integrations\plaid\plaidIntegration.js, line 126.
> 
> You should then be able to add accounts from a new country.

Thanks ! I find the plaidIntegration.ts, line 126 in src folder. But there is no "lib" folder. Can't find any other file where country codes are mentioned. Only changing line 126 doesn't do the trick..

I appreciate the help !

**Comment by SuperAtic** [comment]
What about Australia?

**Comment by LeontiBrechko** [comment]
> Hi @jacobdtapper
> 
> > Once you've installed through npm install go to mintable\lib\integrations\plaid\plaidIntegration.js and change line 179:
> > `country_codes: ['US'],` to your country.
> > Do the same in mintable\lsrc\integrations\plaid\plaidIntegration.js, line 126.
> > You should then be able to add accounts from a new country.
> 
> Thanks ! I found the plaidIntegration.ts, line 126 in src folder. But there is no "lib" folder. Can't find any other file where country codes are mentioned. Only changing line 126 doesn't do the trick..
> 
> I appreciate the help !

For me, changing [line 126](https://github.com/kevinschaich/mintable/blob/master/src/integrations/plaid/plaidIntegration.ts#L126) to `                    country_codes: ['CA'], // TODO` (for Canada) worked well

**Comment by kevinschaich** [comment]
Thanks guys. I added some docs to the FAQs section of the  README here in https://github.com/kevinschaich/mintable/commit/cf3bf811e5f7a2429a59847b7e731120e0cefcab.
