### ISSUE TITLE
Allow renaming of synced accounts

### ISSUE THREAD

**Issue by DouglasRose** [kevinschaich/mintable#124]
It'd be great to be able to rename account

For example, I have two Metro Bank accounts. Both are called 'Current Account' in the Account field in the Google Sheet and it's impossible to differentiate between them when I'm reviewing transactions

**Comment by mazzarin** [comment]
+1! or in lieu of this, please consider support for the account_id field

**Comment by kevinschaich** [comment]
Hey @DouglasRose @mazzarin  – I'd encourage you to explore all the available properties in the Plaid Transactions API:

https://plaid.com/docs/api/products/transactions/

If it's not there, it's not being returned by either Plaid or by your bank. You can experiment with adding non-default ones to this block in your mintable.json

```
    "transactions": {
        "integration": "google",
        "properties": ["date", "amount", "name", "account", "category", "pending"],
   }
```
If you're still not getting the data you need, you could use a [Transaction Override Rule](https://github.com/kevinschaich/mintable/tree/master/docs#transaction-override-rules) to import the account ID/number (unique according to Plaid), and then translate it to a friendly account nickname.
