### ISSUE TITLE
Existing Plaid Connections

### ISSUE THREAD

**Issue by jpartain89** [kevinschaich/mintable#126]
For those of us who have existing plaid developer connections setup, say, through a different self-hosted service that I ended up not liking so i'm trying out your service, and we don't want to use any more of our limited 100 counts of account linking.... How can we utilize those EXISTING setups rather than re-link them and use up more of our slots?

Because, right now, I'm not quite understanding how its linking the plaid connection within the config file or where that ID comes from?

**Comment by kevinschaich** [comment]
Hey @jpartain89 – you can just add any existing accounts to the accounts block like so:

```json
    "accounts": {
        "Chase": {
            "id": "Chase",
            "integration": "plaid",
            "token": "access-development-XXXXXXXXX-XXXXXXXXX-XXXXXXX"
        },
    ...
   }
```
