### ISSUE TITLE
Sub-Account name returning blank

### ISSUE THREAD

**Issue by gnr5** [kevinschaich/mintable#129]
I'm connected to Ally where I have multiple accounts, my transactions are all loading however the "account" and "mask" column is blank so I can't tell which account is which. 

Thanks!

**Comment by kevinschaich** [comment]
Hey @gnr5 – I'd encourage you to explore all the available properties in the Plaid Transactions API:

https://plaid.com/docs/api/products/transactions/

If it's not there, it's not being returned by either Plaid or by Ally. You can experiment with adding non-default ones to this block in your `mintable.json`

```json
    "transactions": {
        "integration": "google",
        "properties": ["date", "amount", "name", "account", "category", "pending"],
   }
```

If you're still not getting the data you need, you could use a [Transaction Override Rule](https://github.com/kevinschaich/mintable/tree/master/docs#transaction-override-rules) to import the account ID/number (unique according to Plaid), and then translate it to a friendly account nickname.
