### ISSUE TITLE
Clarification on Transaction Overrides / Filtering

### ISSUE THREAD

**Issue by mazzarin** [kevinschaich/mintable#130]
In https://github.com/kevinschaich/mintable/pull/96, you added transaction overrides and filtering capabilities, but I'm unable to access this functionality. I suspect it's just user error on my part.

I've tried adding the rules to various parts of mintable.jsonc (usually resulting in a parsing error) and in a separate file named transactions.rules in the same directory as mintable.jsonc (which doesn't appear to be doing anything.)

Can you clarify the best way to use this?

**Comment by mazzarin** [comment]
Turns out it is supposed to be in the mintable.jsonc file. I probably was forgetting a comma. Example below:

  "transactions": {
    "integration": "csv-export",
    "properties": [
      "date",
      "amount",
      "name",
      "account",
      "category"
    ],
    "rules": [
       {
             "conditions": [
                 {
                     "property": "name",
                     "pattern": "(transfer|xfer|trnsfr)",
                     "flags": "ig"
                 }
              ],
             "type": "filter"
        }
    ]
  },

**Comment by mikegriff38** [comment]
Thank you!
