### ISSUE TITLE
Date issues

### ISSUE THREAD

**Issue by jsaltzman** [kevinschaich/mintable#137]
When mintable exports to Google sheets, the date formate is as follows "2022.02.23"

Many budgeting softwares are having trouble parsing this date. Is it possible to change the "." to "-" somehow? I can do this in excel with formulas taking the left and right sides of the date, but would prefer if I could skip this step.

**Comment by kevinschaich** [comment]
Hey @jsaltzman – you should be able to do this with a regex replace via a [Transaction Override Rule](https://github.com/kevinschaich/mintable/tree/master/docs#transaction-override-rules).
