### ISSUE TITLE
OAuth error

### ISSUE THREAD

**Issue by albertple** [kevinschaich/mintable#140]
Getting this error when setting up mintable after entering in Google API credentials (Step 4)

> Error 400: invalid_request
> 
> You can't sign in to this app because it doesn't comply with Google's OAuth 2.0 policy for keeping apps secure.
> 
> You can let the app developer know that this app doesn't comply with one or more Google validation rules.
> Request Details
> The content in this section has been provided by the app developer. This content has not been reviewed or verified by Google.
> If you’re the app developer, make sure that these request details comply with Google policies.
> redirect_uri: urn:ietf:wg:oauth:2.0:oob

**Comment by keeeenion** [comment]
I got around it by just pointing to some random url like: http://localhost:8080.. then after authorization i got the code from the url it redirected me. The page will never load, don't worry.

**Comment by ouhakheme** [comment]
Looks like the OOB flow is deprecated: https://developers.googleblog.com/2022/02/making-oauth-flows-safer.html#instructions-oob

**Comment by j-justice** [comment]
yeah @ouhakheme  I tried setting this up and got this error :( https://i.imgur.com/5h4Z7AA.jpeg

**Comment by vincecao** [comment]
Adding your gmail into testing user field should fix the issue

![image](https://user-images.githubusercontent.com/17363908/187014922-c6a5a33c-36ae-4ec7-8be6-e27b2779297b.png)

![image](https://user-images.githubusercontent.com/17363908/187014940-11205719-3f02-4b04-97d6-8eb1b3e6cb9f.png)

**Comment by kevinschaich** [comment]
What do you guys recommend we update the docs with to make this clearer?

**Comment by kevinschaich** [comment]
Thanks @vincecao – I added instructions in the Google Setup flow here https://github.com/kevinschaich/mintable/commit/5b80c5ee45448196515f4e0dfcc70810d614203f to help people that run into this in the future. Appreciate your help.
