### ISSUE TITLE
Where to find Transaction.rules and how to edit institution names

### ISSUE THREAD

**Issue by werei** [kevinschaich/mintable#154]
I'm not sure where I can go for help as every time I google mintable it's the NFT stuff. If there is a better place, I will go there.

I would like to note that I am on Windows 11. Everything seems to be going smoothly though, and I am using github to automate refreshes.

But I am having trouble with a couple of things.

1. I can't seem to find Transaction.rules config. Do I need to make that myself?
2. How can I change the name of an institution? I have been looking all over for a way (which brought me to the transaction.rules config), but I can't seem to find anything concrete. Currently, some accounts will just say "Saving Account" and not the institution. I would prefer if I can name it whatever I want.
3. Not an issue, but I noticed there is public template (or was) but I can't seem to find it anywhere. Maybe this is no longer a thing, and that is okay, but it would be cool to use if it is still out there.

I am very new to this, and when I found out I could budget using live data I was super excited to get started. I know very little code and only know some due to my work, so writing it is very difficult for me. But if I can be provided an example to work with, I am usually okay to take it from there and figure out the rest.

**Comment by Rukarn** [comment]
#130 maybe

**Comment by werei** [comment]
> #130 maybe

Thank you! So it's all in the one jsonc file. I would have never guessed that. I'm not much of a coder, but I'll have to see if I can figure it out.
