### ISSUE TITLE
Plaid not connecting

### ISSUE THREAD

**Issue by mlelien** [kevinschaich/mintable#161]
Hello! I'm trying to link my accounts on Plaid. I'm on the developer environment for Plaid. Every different financial institution I connect to gives the Plaid error "Something went wrong. Internal error occurred". There's no error on the terminal from Mintable. It's saying that everything was successful. I tried setting up Mintable twice to make sure it wasn't a human error on my part. Same results both times.

> 2023-08-01T03:00:35.978Z [INFO] Using default configuration file `/Users/el/mintable.jsonc.`
> 2023-08-01T03:00:35.979Z [INFO] You can supply either --config-file or --config-variable to specify a different configuration.
> 2023-08-01T03:00:35.979Z [INFO] Successfully opened configuration file.
> 2023-08-01T03:00:35.980Z [INFO] Successfully parsed configuration.
> 2023-08-01T03:00:37.041Z [INFO] Successfully validated configuration.
> 2023-08-01T03:00:37.041Z [INFO] Account setup in progress.
> 2023-08-01T03:00:39.644Z [INFO] Successfully created Plaid link token.
> 2023-08-01T03:01:03.644Z [INFO] Account is OK, no further action is required.
> 2023-08-01T03:01:03.646Z [INFO] Successfully set up Plaid Account(s).
> 2023-08-01T03:01:03.646Z [INFO] Plaid authentication exited.

**Comment by logan-life** [comment]
Same for me -- see this issue, I might have found the solution. 

https://github.com/kevinschaich/mintable/issues/165#issuecomment-1702903229

**Comment by logan-life** [comment]
Solved this for me by logging into Plaid dashboard and verifying with Plaid for Development Environment access. See that thread for more details on how to look at more detailed error logs in Plaid to diagnose this.

**Comment by amahpour** [comment]
> Solved this for me by logging into Plaid dashboard and verifying with Plaid for Development Environment access. See that thread for more details on how to look at more detailed error logs in Plaid to diagnose this.

Ditto on this one. Ran into the same issue and that was the solution. @logan-life were you able to issue a PR with the docs updated to reflect this? I didn't see a linked PR to #165.

@mlelien Can we close this issue?
