### ISSUE TITLE
country_code no longer working

### ISSUE THREAD

**Issue by dddd-zdf** [kevinschaich/mintable#172]
forked, edited, installed & setup the whole thing as instructed but the plaid account page is showing US banks only. 
![image](https://github.com/kevinschaich/mintable/assets/5017696/a10ad56e-3da6-4300-8b99-838be32c84a6)

**Comment by dddd-zdf** [comment]
tried to debug but im not so familiar with ts. tried console.log() and logInfo() but neither seems to print anything

**Comment by dddd-zdf** [comment]
im so confused. any change i made had no effect at all. do i have to manually rebuild or something?

**Comment by logan-life** [comment]
@dddd-zdf yes, you need to [rebuild](https://github.com/kevinschaich/mintable/blob/master/docs/README.md#development) after you make changes to the code. 

make your changes, save the file, then `npm run build`

**Comment by raphaelg** [comment]
@dddd-zdf : you can also just start the all thing like this to have both Canadian and US banks if you don't want to rebuild:
`COUNTRY_CODES=CA,US mintable account-setup`
