### ISSUE TITLE
On June 20, 2024, the Plaid Development environment will be decommissioned.

### ISSUE THREAD

**Issue by DorianMazur** [kevinschaich/mintable#177]
<img width="775" alt="image" src="https://github.com/kevinschaich/mintable/assets/46839236/8b5a4ac7-cff1-4306-99a8-ebe50b1d2156">
Are you planning to switch to another provider? For example GoCardless?

**Comment by kevinschaich** [comment]
https://plaid.com/docs/changelog/

![image](https://github.com/kevinschaich/mintable/assets/9244728/e71cafb2-5527-4b87-b26b-a8ba29968acb)

Think it's fine
