### ISSUE TITLE
Pluggable interface for transaction data

### ISSUE THREAD

**Issue by kevinschaich** [kevinschaich/mintable#2]
As mentioned on [HN thread](https://news.ycombinator.com/item?id=19014820) – there are some security concerns about using Plaid.

As mentioned on [Reddit thread](https://www.reddit.com/r/javascript/comments/akidk9/mintable_a_rollyourown_mint_clone_for_managing/) – some users have banks which are not supported with Plaid.

**Comment by johnwiseheart** [comment]
This is awesome! it looks like [TrueLayer](https://truelayer.com/) is plaid for UK banks - how do you feel about adding this in as a pluggable interface? I have both UK and US accounts - so it would be cool to allow both currencies simultaneously, but that might add more complexity.

**Comment by kevinschaich** [comment]
Hey John – sounds good to me! We'll probably need to figure out how to map those two together to account for API differences, but shouldn't be a problem.

I just opened #9 which should make it easier to drop in a new provider. I'll stick you on that as a reviewer.
