### ISSUE TITLE
Customizable host/port

### ISSUE THREAD

**Issue by ncstdc** [kevinschaich/mintable#30]
Is it possible to customize the host and port for the web interface. The port option does exist as shown below, but isn't used and 3000 is hardcoded everywhere else. 

https://github.com/kevinschaich/mintable/blob/fe72e3d8283c247a4effec4aa143d20565edb604/src/scripts/setup.js#L17

**Comment by kevinschaich** [comment]
Hey @ncstdc – 

I think this should be fixed via #31 in [release `v1.2.2`](https://github.com/kevinschaich/mintable/releases/tag/1.2.2):

>This release adds configurable [hosts](https://github.com/kevinschaich/mintable/blob/master/docs/CONFIG.md#host) and [ports](https://github.com/kevinschaich/mintable/blob/master/docs/CONFIG.md#port).

Let me know if this fits your needs.

**Comment by ncstdc** [comment]
It does, thanks!
