### ISSUE TITLE
Category list

### ISSUE THREAD

**Issue by neomicho85** [kevinschaich/mintable#32]
Where do you create or get the list of Categories and Subcategories (category.1), based on what? How to add my own categories?

**Comment by kevinschaich** [comment]
Hey @neomicho85 – those categories are assigned automatically from Plaid’s servers before they are even retrieved by Mintable – but sometimes they’re not always 100% correct. In my case, every month my Chase credit card payment was getting categorized as a “restaurant,” which is obviously wrong and threw off some of my spreadsheet formulas.

Mintable allows you to override/change the category assigned to a transaction based on a pattern, it’s detailed in the [config docs](https://github.com/kevinschaich/mintable/blob/master/docs/CONFIG.md#category-overrides). Can you give that a try and let me know if you’re having trouble or if the docs are unclear?

**Comment by neomicho85** [comment]
Thx @kevinschaich. I can see, Plaid assign the categories, I use "**Build your own mint**" to check that info

But what about the: 
Monthly Summary?
Category Breakdown: category, budget columns (where they come from?) 
Where is the code that build all that info?

How to customize the template spreadsheet?

**Comment by neomicho85** [comment]
I was trying to use the "template" in my own spreadsheet but the next pages doesn't (the generates with mintable) doesn't get the template format... There is any way to work with that?

**Comment by kevinschaich** [comment]
Hey @neomicho85 – it sounds like you're pretty close. Check out the [Template Spreadsheet](https://github.com/kevinschaich/mintable/blob/master/docs/CONFIG.md#template-sheet) section of the config docs – I think if you update that section to match what you've added in your own spreadsheet you should be in business.

**Comment by kevinschaich** [comment]
Hey @neomicho85 – friendly check-in? Let me know if you've figured it out, if you need any additional help, or if we're OK to close out this out 🙂

**Comment by neomicho85** [comment]
@kevinschaich thanks for your attention. Mintable is excellent, but since Plaid is not well formatting the categories and subcategories it is difficult to work in my own business logic.
