### ISSUE TITLE
Duplicate Transactions?

### ISSUE THREAD

**Issue by henry74** [kevinschaich/mintable#33]
I've been noticing a lot of duplicate transactions in the mintable spreadsheet.  Doesn't seem to be a rhyme or reason as it happens with both pending and completed transactions.  I understand the tabs are cleared and recreated so I assume these are coming from plaid - how can we validate?

**Comment by kevinschaich** [comment]
Hey Henry,

Not sure we provide a clean way to debug this out of the box, but if you're comfortable, (and are on the latest version), try adding the following:

```javascript
console.log(JSON.stringify(transactions, null, 2))
```

right before line 113 in `plaid.js`:

https://github.com/kevinschaich/mintable/blob/8ecd05da69ea666f2e434cb25196afcd9db5fb5a/src/lib/plaid.js#L113

That will output the raw source of the transactions from Plaid and help us figure out if there's some weirdness going on. Let me know!

**Comment by henry74** [comment]
Just pulled the latest version and all the duplicates disappeared after I reran `yarn mintable`.  I'm guessing the latest commits fixed whatever was causing the duplicates.  I'll keep on eye on the transactions.  Closing for now.
