### ISSUE TITLE
returning account properties of associated plaid transactions via config

### ISSUE THREAD

**Issue by ak2k** [kevinschaich/mintable#34]
It would be nice to be able to return other account properties (e.g. 'subtype', 'mask') by adding them to TRANSACTION_COLUMNS

**Comment by kevinschaich** [comment]
Hey @ak2k, have you seen the [`TRANSACTION_COLUMNS`](https://github.com/kevinschaich/mintable/blob/master/docs/CONFIG.md#transaction-columns) sections of the docs? If the properties are returned by Plaid, you should be able to access them there.

Can you try adding `subtype` or perhaps `account_details.subtype` to your `TRANSACTION_COLUMNS` config?

**Comment by kevinschaich** [comment]
Hey @ak2k – this is already supported and haven't heard anything on this issue for a while. Suggest checking the config property linked above, let me know if you're having trouble.

**Comment by ak2k** [comment]
Hey @kevinschaich,
Apologies for the slow reply on this one. I have tried both, and each results in an empty column in the output sheet (no data).

**Comment by kevinschaich** [comment]
Do other columns (i.e. the defaults) return the data you expect?

You can try enabling [`DEBUG MODE`](https://github.com/kevinschaich/mintable/blob/master/docs/CONFIG.md#debug-mode) to see what's returned by Plaid and whether those columns actually exist in the transaction data. It differs slightly from provider-to-provider and maybe those fields just happen to be blank for your bank.

If you want to post a redacted version of the debug output & your config here I can try to dig in further with you.

**Comment by ak2k** [comment]
Thank you for your note!

Could the confusion be that I'm looking to add to the sheet properties of
accounts (e.g. subtype) that are not included in the plaid-returned
transactions array itself, but would need to be looked up in the accounts
array for each transaction? Does mintable do that lookup for transactions
today or does it just match column names?

Happy to send along debugs if you would expect this to work!

**Comment by kevinschaich** [comment]
@ak2k – I think I understand now – we're not including all the account details by default:

https://github.com/kevinschaich/mintable/blob/52a8a2f0a8af4fd49c348a046afc22ddebb2c927/src/lib/plaid.js#L146-L158

Should be easy enough to add these in.

**Comment by kevinschaich** [comment]
Let me know if #45 would do the trick for you.

**Comment by ak2k** [comment]
It sure does, thank you! I confirmed that adding 'account_details.subtype'
to TRANSACTION_COLUMNS works as expected. Thank you again!
