### ISSUE TITLE
Error fetching sheets for spreadsheet id <id>

### ISSUE THREAD

**Issue by jbcurrie** [kevinschaich/mintable#36]

**Comment by dckc** [comment]
I just saw these same symptoms after following the README directions. In particular, `yarn setup` seemed to go as planned, but `yarn mintable` said:

```
$ yarn mintable
yarn run v1.12.3
$ node ./src/scripts/mintable.js

Using config /home/connolly/projects/mintable/mintable.config.json.
Note: The messages displayed below are automated and may contain duplicates.

  ✔ Fetching current config
  ✔ Fetching transactions for account DISCOVER
  ✔ Fetching transactions for accounts
  ✔ Fetching balance for account DISCOVER
  ✔ Fetching balances for accounts
  ✖ Error fetching sheets for spreadsheet id 1-6...be:

    { error: 'Error: The caller does not have permission' }

error Command failed with exit code 1.

```

**Comment by kevinschaich** [comment]
Hey @dckc – apologies you're having issues – can you please post a redacted version of your config JSON here? You can omit all tokens/values and just keep maybe the first and last character.

Just want to make sure everything that should have a value is filled in.

**Comment by kristian-mypos** [comment]
× Error formatting sheets :

    { error: 'Error: Must specify at least one request.' }

error Command failed with exit code 1.

**Comment by kevinschaich** [comment]
Suspect this is fixed in the latest version: https://github.com/kevinschaich/mintable/releases/tag/1.2.6.

Suggest you guys try upgrading – if you're still seeing issues you can [enable `DEBUG` mode](https://github.com/kevinschaich/mintable/blob/master/docs/CONFIG.md] and paste the results here and we can dig in further.
