### ISSUE TITLE
Different providers for different accounts?

### ISSUE THREAD

**Issue by dflock** [kevinschaich/mintable#41]
I have some WealthSimple accounts. Plaid doesn't support WealthSimple, afaik. However, WealthSimple have their own REST API: https://developers.wealthsimple.com/ - which looks like it does everything you'd need.

I'm happy to write a provider for WealthSimple. However, I'm not sure how to use it? I only see a single `ACCOUNT_PROVIDER` config setting? I have some accounts with banks that Plaid does support, as well as the WealthSimple accounts - so I'd need to set a provider on a per-account basis, maybe?

Is there currently a way to say "Get data for these accounts from this provider, and use this other provider for these accounts"?

**Comment by dflock** [comment]
Hmmmmm... Is the intention that I use a separate instance of Mintable for this - one provider (and one Spreadsheet) per instance?

I'd want this to work like Mint.com I think - and have everything from all my accounts flow into one place - although I'm not sure what the spreadsheets for that would look like?

**Comment by kevinschaich** [comment]
Hey @dflock – thanks for the issue, your understanding is correct. The assumption I made when adding providers was that people would pick one provider for all their accounts, for a variety of reasons (maybe they're in Europe vs. the U.S., maybe they don't trust Plaid or Google for one reason or another, etc). I have a few accounts myself that don't integrate nicely with Plaid (Apple Card for one), so I can definitely see this being valuable for people. What I don't want for Mintable is to "become" the API itself, i.e. if _everyone_ makes a pull request to support their own local credit union; the complexity and support burden both increase significantly.

I think we could support per-account providers at some point – but it would probably be a large-ish undertaking. A lot of the core `mintable.js` code would need to change to branch at each point you handle account data; you'd need to import the respective provider code, fetch transactions/balances, manipulate the data back into the generic Mintable format, and then pass it to the next step

If you want to add this feature via a PR I'm happy to be a thought partner, but I don't have the time for this level of rewrite any time soon.

**Comment by kevinschaich** [comment]
Fixed in #66 – discussion in #55
