### ISSUE TITLE
Config error nukes config file

### ISSUE THREAD

**Issue by Naddiseo** [kevinschaich/mintable#53]
I was editing the config file (trying to change the template location) and must of missed, or added, an extra comma, which caused it to be overwritten with the initial layout. This lost all the API keys for plaid and google sheets. Specifically it's the plaid ones that annoyed me since we only get a certain amount of linked accounts, but I know don't know that item id.

It might be an idea not to nuke existing config files on error, or store the API keys in a separate file after initial setup.

(I should also make backups, I know, but it's also preventable, and unexpected behaviour)

**Comment by kevinschaich** [comment]
Hey @Naddiseo – appreciate you filing an issue for this and sincerely apologize for the inconvenience, I know it was frustrating to encounter this bug.

I'll make sure we prioritize fixing this for the 2.0.0 milestone.

**Comment by kevinschaich** [comment]
Fixed in #66 – discussion in #55
