### ISSUE TITLE
Retrieve transactions in google sheets tab "transactions"

### ISSUE THREAD

**Issue by lecoffeeguy** [kevinschaich/mintable#60]
Hi there,

I'm not a programmer and I have learned some basic coding skills over the years; I'm also a personal finance geek so this is just an amazing project for me !

That being said, I have already built my own google sheet template and I would like to use your code to retrieve the transactions and update the google sheet in the tab "transactions" (instead of spreading it into a tab per month). 

Thanks !

**Comment by kevinschaich** [comment]
Hey @lecoffeeguy – thanks for filing an issue. 

Further explanation on https://github.com/kevinschaich/mintable/issues/44#issuecomment-579921177 but we're probably not going to support this. To allow exporting everything to a single sheet would require lots of additional housekeeping to track & deduplicate individual transactions. 

Thanks for using mintable!
