### ISSUE TITLE
Bug: v2.0.0 Beta - mintable setup -> linking a new account successfully doesnt show the account

### ISSUE THREAD

**Issue by yawhide** [kevinschaich/mintable#73]
When you link a new account using `mintable setup` and successfully connect the account to plaid, the main screen doesnt refresh. You cant see your newly created account. You need to refresh manually to see the connected account.

(small issue)

**Comment by kevinschaich** [comment]
Thanks @yawhide – I think this is fixed in #76. Refreshing after the Plaid auth result should do the trick.

Can you confirm whether this fixes the issue on `v2.0.0-beta.32`?

You should be able to upgrade versions by running:

```bash
npm install -g mintable
```

**Comment by yawhide** [comment]
looks good now!
