### ISSUE TITLE
Enhancement: Overwrite Plaid Categories

### ISSUE THREAD

**Issue by mspych** [kevinschaich/mintable#78]
Would be nice to be able overwrite the categories from Plaid from some sort of dictionary.

**Comment by kevinschaich** [comment]
Hey @mspych – thanks for the idea, and I agree!

Already planned on the roadmap for 2.1.0: https://github.com/kevinschaich/mintable/issues/57

I'll mark this as a duplicate for now. Thanks!

**Comment by kevinschaich** [comment]
Hey @mspych – this is fixed in #96 / `v2.0.0-beta.44`!

**Comment by mspych** [comment]
Fantastic! 
Thank you.
