### ISSUE TITLE
Bug: v2.0.0 Beta - Ability to delete accounts

### ISSUE THREAD

**Issue by yawhide** [kevinschaich/mintable#81]
Hello,

I added an 3 accounts from TD Canada Trust after running `mintable account-setup` and then ran `mintable fetch`. Everything worked.

I then realized i only wanted to grab transactions from 1 of the 3 accounts. So I clicked update to see if there was a way to "deselect" two of the accounts from plaid. But instead when I click update I see
![image](https://user-images.githubusercontent.com/5014112/85934931-0d02c500-b8b8-11ea-94d7-3d5f29a91043.png)

I also do not see a way to delete an account from the `account-setup` page either. 

What is the correct way to remove some accounts?

Thanks

**Comment by kevinschaich** [comment]
Thanks @yawhide – hope you don't mind I've updated the title to `Ability to delete accounts`. Agree this is an important feature.

For anyone viewing this issue, as a friendly heads up (I learned this the hard way) – removing accounts from Mintable will not add credits back to your 100 accounts on the Plaid Free plan. Once you authenticate for the first time, it will count towards your 100. For this reason I do most of my testing in the sandbox environment, and then once I am confident things are working I will switch to development and use my real credentials.

**Comment by kevinschaich** [comment]
Hey @yawhide – added this feature in #84 / `v2.0.0-beta.36`:

<img width="1286" alt="Screen Shot 2020-06-30 at 10 59 54 PM" src="https://user-images.githubusercontent.com/9244728/86198751-548e8880-bb26-11ea-9989-62c7d50d4851.png">

Can you try this out and see if it fixes the issue for you?

**Comment by yawhide** [comment]
love the new styling!

**Comment by kevinschaich** [comment]
Apologies @yawhide forgot to include the static/docs folder in the NPM bundle – can you try one more time for me on `v2.0.0-beta.37`?

**Comment by yawhide** [comment]
![image](https://user-images.githubusercontent.com/5014112/86259797-7588c500-bb8a-11ea-9206-60cae48611f3.png)

looking good

**Comment by yawhide** [comment]
also i was able to delete an account successfully

**Comment by a-arbabian** [comment]
@yawhide Hey, is your TD Canada Plaid setup still working? I only see `tdbank.com` in the list of institutions for `mintable account-setup` and that seems to be for the US TD accounts. 
Thanks for any help!
