### ISSUE TITLE
Enhancement: Provide a Docker image to run Mintable

### ISSUE THREAD

**Issue by Zeustopher** [kevinschaich/mintable#82]
I love the idea of Mintable and being able to own my own financial data! Keep it up!

But manually installing node, yarn, etc etc isn't something I'm too fond of doing... Instead, I'd _love_ to have a Docker :whale: image that I could run this in! I already self-host a few services on an Ubuntu server so this would happily live alongside those.

The office node image comes with yarn preinstalled: https://hub.docker.com/_/node/ so it should be a pretty good jumping point in getting a docker image created.

Ultimately it would be great if there could be images built whenever a release takes place and pushed to docker hub so we could just pull from it and launch. It would make upgrading to new versions a piece of cake.

**Comment by Zeustopher** [comment]
I see in your v2 branch you've simplified it to only use npm, but I would still love a container that is just ready to launch (already has all the npm dependencies in the container, etc) and send me right into the configuration of it.

**Comment by kevinschaich** [comment]
Hey @Zeustopher – thanks for filing an issue!

I don't think we'll prioritize this right now as this is the first time I've heard any complaints about the dependencies.

The `v2.0.0` release is about as lightweight as I can make it (a global command line utility) without compiling a binary for each operating system – the only thing you need as a prerequisite is `node` & `npm` (I think they even come bundled together nowadays). That's a pretty common set of prereqs that I think you'll find for most JavaScript based open source projects.

That being said, if you do create a containerized version, let me know and we can add instructions to the docs in case others want to do the same!
