### ISSUE TITLE
Request: allow transactions and balance sheets to use the account nickname from Plaid

### ISSUE THREAD

**Issue by Nojwe** [kevinschaich/mintable#98]
It would be great if we could use the account name we assign in Plaid instead of what Plaid returns in case of blanks for both balances and transactions: 

![image](https://user-images.githubusercontent.com/46374242/87444587-f8674200-c5c4-11ea-9bd9-efed35cd0a32.png)

E.G. instead of just 'Emergency Fund', pull in the Plaid account nickname I set of 'Ally'

**Comment by kevinschaich** [comment]
Hey @Nojwe – we removed account nicknames in `v2.0.0` - so I'm guessing there may be some skeletons here from your `1.x.x` config.

You could accomplish what you want with a [Transaction Override](https://github.com/kevinschaich/mintable/tree/release/2.0.0/docs#transaction-override-rules) for your transactions sheets. I don't think we have a good way to do this for balances but we could pretty easily add an optional `nickname property`.

**Comment by Nojwe** [comment]
The Transaction Override should work fine with some simple conditions. Thanks!
